#
#spring.datasource.url=jdbc:mysql://localhost/nft?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=seekaappuser
#spring.datasource.password=dgE4CUaz~+Z%yZ=_
#spring.datasource.platform=mysql
#spring.datasource.initialization-mode=always
#spring.jpa.hibernate.ddl-auto=update

spring:
  application:
    name: nft-sync-service
  data:
    mongodb:
      uri: mongodb+srv://TradeScrap:TradeScrap@cluster0-8570y.mongodb.net/NFT_Matcher?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      repositories:
        enabled: true
        
simpleHash:
  apiKey: segmint_sk_f053f4b7-98e5-4c82-a1b9-8a409bef90b0_a01tnii6qimceimn