spring:
  application:
    name: nft-sync-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_QEpROgOaY
          jwk-set-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_QEpROgOaY/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb+srv://TradeScrap:TradeScrap@cluster0-8570y.mongodb.net/nft
      repositories:
        enabled: true